language: node_js
sudo: required
node_js: 
  - 11.1.0
cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

before_install:
  - npm install -g hexo-cli

install:
  - npm install

before_script:
  - git config user.name "libery"
  - git config user.email "szq921618920@gmail.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GITHUB_TOKEN}/g" _config.yml || exit 1

script:
  - hexo clean
  - hexo generate
  - hexo deploy