language: node_js
sudo: required
node_js: 
  - 11.1.0
cache:
  directories:
    - node_modules

branches:
  only:
    - hexo 

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "libery"
  - git config user.email "szq921618920@gmail.com"
  - git add .
  - git commit -m "TravisCI"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/Thewhitelight/Thewhitelight.github.io.git" master:master