name: HEXO CI

on:
  push:
    branches:
    - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ~/.ssh/blogDeploy
          chmod 600 ~/.ssh/blogDeploy
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cat ~/.ssh/blogDeploy
          echo "============="
          cat ~/.ssh/known_hosts
          git config --global user.name "libery"
          git config --global user.email "szq921618920@email.com"
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo clean && hexo generate && hexo deploy